[package]
name = "xpr"
version = "0.1.0"
edition = "2021"
description = "X Portable Runtime for Rust"
authors = [
    "Varphone Wong <varphone@qq.com>"
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[build-dependencies]
bindgen = "0.63"

[features]
default = []
